//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Entity.MemberShip
{

    using System;
    using System.Collections.Generic;

    /// <summary>
    /// 应用程序信息
    /// </summary>
    public partial class Applications
    {
        /// <summary>
        /// 置应用程序的名称
        /// </summary>
        public string ApplicationName { get; set; }
        /// <summary>
        /// 小写的应用程序名
        /// </summary>
        public string LoweredApplicationName { get; set; }
        /// <summary>
        /// 应用程序的Id, GUID值
        /// </summary>
        public System.Guid ApplicationId { get; set; }
        /// <summary>
        /// 应用程序的描述
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// 应用程序信息相关成员信息
        /// </summary>
        public virtual ICollection<Membership> Membership { get; set; }

        /// <summary>
        /// 应用程序信息相关路径信息
        /// </summary>
        public virtual ICollection<Paths> Paths { get; set; }

        /// <summary>
        /// 应用程序信息相关角色表
        /// </summary>
        public virtual ICollection<Roles> Roles { get; set; }

        /// <summary>
        /// 应用程序信息相关用户表
        /// </summary>
        public virtual ICollection<Users> Users { get; set; }
    }
}
