//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fx.Entity.MemberShip
{
    
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 模式版本 Membership中不对外开放
    /// </summary>
    public partial class SchemaVersions
    {
        /// <summary>
        /// 特性
        /// </summary>
        public string Feature { get; set; }

        /// <summary>
        /// 不支持的模式类型
        /// </summary>
        public string CompatibleSchemaVersion { get; set; }

        /// <summary>
        /// 是否当前版本
        /// </summary>
        public bool IsCurrentVersion { get; set; }
    }
}
